apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e4a8yn29b-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e4a8yn29b-go 
  name: e4a8yn29b-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: e4a8yn29b-go 
